In [8]:
from numpy import *
random.rand(4,4)#这是个数组 array

array([[ 0.48924329,  0.8229303 ,  0.4207627 ,  0.72941294],
       [ 0.58169073,  0.37790686,  0.2791561 ,  0.86786383],
       [ 0.29027585,  0.89255035,  0.74389389,  0.22693735],
       [ 0.68061284,  0.69555243,  0.63719436,  0.27196451]])

In [9]:
type(random.rand(4,4))

numpy.ndarray

In [10]:
# 将数组转换成矩阵
randMat = mat(random.rand(4,4))
randMat

matrix([[ 0.8419623 ,  0.23343004,  0.88749904,  0.69332503],
        [ 0.44559237,  0.9654768 ,  0.18637033,  0.04499227],
        [ 0.20374883,  0.82314108,  0.45169068,  0.36132179],
        [ 0.93076536,  0.5255061 ,  0.85453615,  0.84796703]])

In [11]:
# 矩阵求逆
invRandMat = randMat.I
invRandMat

matrix([[-0.02643088,  1.43341472, -2.25150272,  0.90492859],
        [-0.68078491,  0.47845718,  0.69724486,  0.23414659],
        [ 4.6002563 , -0.11719095,  1.68991823, -4.47517924],
        [-4.18498314, -1.75179102,  0.33623727,  4.55074389]])

In [12]:
randMat * invRandMat

matrix([[  1.00000000e+00,   0.00000000e+00,   2.77555756e-16,
          -4.44089210e-16],
        [ -8.32667268e-17,   1.00000000e+00,   1.71737624e-16,
           0.00000000e+00],
        [ -2.22044605e-16,   1.11022302e-16,   1.00000000e+00,
           2.22044605e-16],
        [  0.00000000e+00,  -2.22044605e-16,   6.10622664e-16,
           1.00000000e+00]])

In [13]:
# 单位矩阵
myEye = randMat * invRandMat
myEye - eye(4)

matrix([[  8.88178420e-16,   0.00000000e+00,   2.77555756e-16,
          -4.44089210e-16],
        [ -8.32667268e-17,   0.00000000e+00,   1.71737624e-16,
           0.00000000e+00],
        [ -2.22044605e-16,   1.11022302e-16,  -2.22044605e-16,
           2.22044605e-16],
        [  0.00000000e+00,  -2.22044605e-16,   6.10622664e-16,
           0.00000000e+00]])